apiVersion: skaffold/v3
kind: Config
metadata:
  name: mcpbot
profiles:
- name: services-staging
  build:
    googleCloudBuild:
      projectId: dl-sre-staging
      kanikoImage: gcr.io/kaniko-project/executor
      machineType: N1_HIGHCPU_8
    tagPolicy:
      gitCommit: {}
    artifacts:
      - image: us-west1-docker.pkg.dev/dl-sre-staging/demo/mcpbot
        context: .  # Update to point to root of project
        kaniko:
          dockerfile: Dockerfile  # Update to correct path
          buildArgs:
            SERVICE_DIR: mcpbot
          cache:
            ttl: 24h
            repo: us-west1-docker.pkg.dev/dl-sre-staging/demo/mcpbot
- name: local
  build:
    local:
      useBuildkit: true
    tagPolicy:
      gitCommit: {}
    artifacts:
      - image: us-west1-docker.pkg.dev/dl-sre-staging/demo/mcpbot
        context: .
        docker:
          dockerfile: Dockerfile
          buildArgs:
            SERVICE_DIR: mcpbot