apiVersion: skaffold/v3
kind: Config
metadata:
  name: prototype
profiles:
- name: local
  build:
    local:
      useBuildkit: true
    artifacts:
      - image: us-west1-docker.pkg.dev/dl-sre-staging/demo/prototype
        context: .
        docker:
          dockerfile: Dockerfile