apiVersion: skaffold/v3
kind: Config
metadata:
  name: prototype
profiles:
- name: local
  build:
    local:
      useBuildkit: true
    artifacts:
      - image: prototype
        context: src
        docker:
          dockerfile: Dockerfile
    tagPolicy:
      customTemplate:
        template: "latest"