apiVersion: skaffold/v3
kind: Config
metadata:
  name: prototype
profiles:
- name: local
  build:
    local:
      useBuildkit: true
      push: true
    artifacts:
      - image: us-west1-docker.pkg.dev/dl-sre-staging/demo/prototype
        context: src
        docker:
          dockerfile: Dockerfile
    tagPolicy:
      customTemplate:
        template: "latest"