name: Deploy Static Files
on:
  workflow_dispatch:
    inputs:
      target_folder_name:
        required: true
        description: Name of the folder you are trying to deploy
  workflow_call:
    inputs:
      target_folder_name:
        required: true
        type: string
        description: Name of the folder you are trying to deploy

permissions:
  contents: read
  packages: write

env:
  DEPLOY_FOLDER: ${{ github.event.inputs.target_folder_name }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy Static Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Building
        uses: dapperlabs/actions/skaffold@v0.1.12
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        with:
          skaffold_action: build
          skaffold_profile: services-staging
          deployment_check: false
          gcp_project: ${{ env.GCP_PROJECT }}
          cluster_name: ${{ env.CLUSTER_NAME}}
          region: ${{ env.REGION}}
          working_directory: cmd/${{ matrix.service }}