name: Deploy Static Files
on:
  workflow_dispatch:
    inputs:
      target_folder_name:
        required: true
        description: Name of the folder you are trying to deploy
  workflow_call:
    inputs:
      target_folder_name:
        required: true
        type: string
        description: Name of the folder you are trying to deploy

permissions:
  contents: read
  packages: write

env:
  DEPLOY_FOLDER: ${{ github.event.inputs.target_folder_name }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy Static Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
