name: Deploy Static Files
on:
  workflow_dispatch:
    inputs:
      target_folder_name:
        required: true
        description: Name of the folder you are trying to deploy
  workflow_call:
    inputs:
      target_folder_name:
        required: true
        type: string
        description: Name of the folder you are trying to deploy

permissions:
  contents: read
  packages: write

env:
  DEPLOY_FOLDER: ${{ github.event.inputs.target_folder_name }}

jobs:
  deploy:
    name: Deploy Static Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/
          rm skaffold

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: Prepare source directory
        run: |
          mkdir -p src
          cp -r ${{ inputs.target_folder_name }}/* src/
          echo "Contents of src directory:"
          ls -la src/

      - name: Building
        run: skaffold build -f skaffold.yaml -p local
        env:
          TARGET_FOLDER: ${{ inputs.target_folder_name }}