name: Deploy Static Files
on:
  workflow_dispatch:
    inputs:
      target_folder_name:
        required: true
        description: Name of the folder you are trying to deploy
  workflow_call:
    inputs:
      target_folder_name:
        required: true
        type: string
        description: Name of the folder you are trying to deploy

permissions:
  contents: read
  packages: write

env:
  DEPLOY_FOLDER: ${{ github.event.inputs.target_folder_name }}

jobs:
  deploy:
    name: Deploy Static Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.DEPLOY_FOLDER }}
      
      - name: Building
        uses: dapperlabs/actions/skaffold@v0.1.12
        with:
          skaffold_action: build
          skaffold_file: ./skaffold.yaml
          skaffold_profile: local
          deployment_check: false
          working_directory: ${{ env.DEPLOY_FOLDER }}